name: iOS CI Metrics

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-test-metrics:
    runs-on: macos-latest

    steps:

      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Install dependencies
      - name: Install Python dependencies
        run: pip install psutil

      # Install CocoaPods (only if Podfile exists)
      - name: Install CocoaPods
        run: |
          if [ -f "Podfile" ]; then
            pod install
          fi

      # Build iOS App
      - name: Build iOS App
        run: |
          xcodebuild \
          -project PerformanceApp.xcodeproj \
          -scheme PerformanceApp \
          -destination 'generic/platform=iOS Simulator' \
          build | tee build.log

      # Run Unit Tests
      - name: Run Unit Tests
        run: |
          xcodebuild \
          -project PerformanceApp.xcodeproj \
          -scheme PerformanceApp \
          -destination 'generic/platform=iOS Simulator' \
          test | tee test.log

      # Generate CI Metrics
      - name: Generate CI Metrics
        run: python3 ci_metrics.py

      # Upload artifact
      - name: Upload Metrics Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci_metrics_history
          path: ci_metrics_history.json

      # Deploy metrics to GitHub Pages
      - name: Deploy dashboard data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          mkdir gh-pages
          cd gh-pages

          git init
          git checkout -b gh-pages

          mkdir -p dashboard
          cp ../ci_metrics_history.json dashboard/

          git add .
          git commit -m "Update CI metrics"

          git remote add origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push --force origin gh-pages
